# config.yaml

# === Model API Keys ===
mistral_api_key: your_mistral_api_key_here
aliyun_api_key: your_aliyun_api_key_here
openai_api_key: your_openai_api_key_here
kimi_latest_128k: your_kimi_api_key_here
gemini_api_key: your_gemini_api_key_here
deepseek_r1_api_key: your_deepseek_api_key_here

# === Usage Example ===
# The benchmark script will automatically read this file to select and invoke the corresponding model.
